name: Node.js CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - name: Install dependencies
      run: |
        npm init -y
        npm install
        npm install express sequelize mysql2 body-parser bcrypt dotenv

    - name: Run basic test
      run: |
        npm test
        echo "running npm test"
