name: Packer Build on GCP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure gcloud CLI
        run: gcloud info

      - name: Set up Packer
        uses: hashicorp/setup-packer@v1
        with:
          packer-version: '1.7.8'  # Specify the Packer version you want to use

      - name: Zip the repository
        run: |
          zip -r webapp.zip .
          mv webapp.zip webapp/packer/shell/

      - name: Create variables file from secrets
        run: |
          cat <<EOF > webapp/packer/variables.pkrvars.hcl
                vpc_name   = "default"
                project_id = "csye6225-414400"
                var_count  = 1
                app_name   = "webapp"
                database   = "db"
                route_next_hop_gateway = "default-internet-gateway"
                route_dest_range = "0.0.0.0/0"
                routing_mode = "REGIONAL"
                GOOGLE_APPLICATION_CREDENTIALS = "service_account_1.json"
                ssh_username = "centos"
            #   variable_name = "${{ secrets.VARIABLE_VALUE }}"
          # Add more variables as needed
          EOF

      - name: Initialize Packer
        run: |
          cd webapp/packer/
          packer init .

      - name: Validate Packer configuration
        run: |
          cd webapp/packer/
          packer validate -var-file="variables.pkrvars.hcl" .

      - name: Run Packer build
        run: |
          cd webapp/packer/
          packer build -var-file="variables.pkrvars.hcl" .
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
